// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadProject(arg1, arg2) {
  return window['go']['main']['App']['LoadProject'](arg1, arg2);
}

export function OpenSpreadsheet() {
  return window['go']['main']['App']['OpenSpreadsheet']();
}

export function OpenSpreadsheetFromPath(arg1) {
  return window['go']['main']['App']['OpenSpreadsheetFromPath'](arg1);
}

export function ProcessSheet(arg1, arg2) {
  return window['go']['main']['App']['ProcessSheet'](arg1, arg2);
}
