// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadProject(arg1:string,arg2:string):Promise<main.Project>;

export function OpenSpreadsheet():Promise<main.SpreadsheetInfo>;

export function OpenSpreadsheetFromPath(arg1:string):Promise<main.SpreadsheetInfo>;

export function ProcessSheet(arg1:number,arg2:main.ColumnMapping):Promise<void>;
